# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false

jobs:
  include:
  - r: devel
  - r: release
